// By - WOODcraft @SudoR2spr
// If you want to add sticker ID add here as per your choice

export const stickerIds = [
    'CAACAgUAAxkBAAEM1dtm7VDhaQ4ONczoBn0kMQlMDDnzcgACiQ8AAmB9uVangRxqcjm23zYE',
    'CAACAgIAAxkBAAEM07Fm6envLIjKfJExwf9VZOXzI8K2WwACMTQAAugboErSr6fEZiaivDYE',
    'CAACAgUAAxkBAAEM1d1m7VDswE7OdPF98Ac81be4_v_WsQACTA4AAsLOuFb14hgAAQzI-y02BA',
    'CAACAgIAAxkBAAEM2Ulm7sVbBPqjgiRejVZ7lYR9ykRhLgACwz0AAswTKUqFD82aGooDRjYE',
    'CAACAgIAAxkBAAEM1c9m7UFdh-7tjFKJa_UuruNTuB_VSAACGgADwDZPE4LbsLU8BkFXNgQ',
    'CAACAgIAAxkBAAEM0yZm6Xz0hczRb-S5YkRIck7cjvQyNQACCh0AAsGoIEkIjTf-YvDReDYE',
    'CAACAgIAAxkBAAEM2Udm7sVJzVyathhzsyRuISjK54BBMgACfz0AAi3JKUp2tyZPFVNcFzYE',
    'CAACAgIAAxkBAAEM2T9m7sUe5IiTmYMwM5Jt-jSeI9LsvwACNS0AAm4DKEomPm8OWEnvtzYE',
    'CAACAgIAAxkBAAEM2U1m7sVpG0bue8flzAmmb6xSjh1rfwACNj8AAvw3SEl-1bzJ-K-rhjYE',
    'CAACAgUAAxkBAAEM2U9m7sacXTvAmUOf2tbPkftVDywtJgACsgsAAp9TsVZLn-4E6phV4DYE',
    'CAACAgUAAxkBAAEM2Tdm7sQh0eIhVvqkKgMEY6CRmNovngACuwsAAvt1sVb5WFKqMYkzKTYE',
    'CAACAgQAAxkBAAEMzLJm483R53GzjAHmbr3ms3iOFSlTqAADFAAClt1hUHmPWNO7Sd_YNgQ'
];
